### ISSUE TITLE
Splitting text nodes into words

### ISSUE THREAD

**Issue by bantuist** [yuanqing/charming#1]
Hey, thanks for making this! There doesn't seem to be an option, but I thought I would ask. Can you wrap words with spans similar to `.lettering('words')` in Lettering.js?

**Comment by LordKayBanks** [comment]
can you please explain what you want better

**Comment by TokaLazy** [comment]
Option for wrap words rather letter ?
@bantuist

**Comment by bantuist** [comment]
Oh, forgot tobreply to this! Yes @TokaLazy, that's what I meant.

**Comment by yuanqing** [comment]
This feature is available as of `2.2.0`
