### ISSUE TITLE
Word split removes spacing

### ISSUE THREAD

**Issue by coolemur** [yuanqing/charming#13]
When I use
```
charming(element, {
  splitRegex: /(\s+)/,
  classPrefix: 'word'
})
```

to split words, spaces are removed. It looks like they are still in DOM, but aren't shown.

Is there a way to split words and keep spaces ?

**Comment by xesjkeee** [comment]
@coolemur

I've found a solution, it looks like this:

```js
const titleNode = document.getElementsByClassName('title')[0]
charming(titleNode)

const charsNodeList = document.querySelectorAll('.title > span')
const charsArrayWithSpace = charsArray.filter(el => {
  if (el.textContent === ' ') el.textContent = ' ' // Here's symbol &#8194;

  return el
})
```

The idea is to change a usual space symbol to the narrow space symbol ``&ensp;``

**Comment by ronca85** [comment]
@coolemur hello!

you can use a non-breaking space instead of a _space_ character in your html

turn `<h1>My Title</h1>` into `<h1>My&nbsp;Title</h1>`

**Comment by yuanqing** [comment]
@coolemur

> Is there a way to split words and keep spaces ?

The regular expression to use is `/\b(?=\S)/`, which is a [positive lookahead](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions#special-lookahead). This will split the `string` on word boundaries (`\b`) that occur immediately _before_ any non-whitespace character (`\S`)

---

> [**Editable demo (CodePen)**](https://codepen.io/anon/pen/QXRgxa)

```html
<h1>foo bar baz</h1>
```

```css
.word-1 {
  color: red;
}
.word-2 {
  color: green;
}
.word-3 {
  color: blue;
}
```

```js
const element = document.querySelector('h1')
charming(element, {
  split: function (string) {
    return string.split(/\b(?=\S)/)
  },
  setClassName: function (index) {
    return `word-${index}`
  }
})
```
