### ISSUE TITLE
use inline-block to enable css transforms

### ISSUE THREAD

**Issue by max-schu** [yuanqing/charming#3]
I suggest to use inline-block in order to enable the use of css transformations.
when settings the span elements zu inline block via css all the blank spaces disappear.

**Comment by yuanqing** [comment]
Certainly, but this is beyond the scope of the module. Module users can style the inserted `span` elements any way they want.

**Comment by max-schu** [comment]
do you know why inline-block elements containing a blank space do not preserve the width?
i couldn't find any specification about this.
